
# Pre-requisites
- name: 'Deploy an e-commerce website'
  hosts: target3
  tasks:

  - name: Pre-requisites packages
    become: true
    yum:
      name:
        - firewalld
        - epel-release  
        - python36-devel  
        - mysql-devel
        - gcc
        - python2-PyMySQL
      state: latest
  
  - name: PIP Install the Python 3.x WITH ROOT #needed for db
    become: true
    pip: 
      name: pymysql
      executable: pip3

  - name: PIP Install the Python mysqlclient module WITH ROOT
    become: true
    pip:
      name: mysqlclient
      executable: pip3

  - name: Start firewalld
    become: true
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Install MariaDb
    become: true
    yum:
      name: mariadb-server
      state: present

  - name: Start MariaDB
    become: true
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Enable port 3306 for MariaDB access
    become: true
    firewalld:
      zone: public
      port: 3306/tcp
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    become: true
    systemd:
      name: firewalld
      state: reloaded   

  - name: Create a new MariaDB database with name 'ecomdb'
    become: true
    mysql_db:
      name: ecomdb
      state: present

  - name: Create MariaDB database user with name 'ecomuser' and password 'ecompassword' with all database privileges
    become: true
    mysql_user:
      name: ecomuser
      password: ecompassword
      priv: '*.*:ALL'
      state: present

  - name: Create load product inventory script
    become: true
    shell:
      cmd: |
        cat > db-load-script.sql <<-EOF
        USE ecomdb;
        CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;

        INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");

        EOF

  - name: Execute script to load product inventory
    become: true
    shell: mysql < db-load-script.sql

# Deploy and configure web

  - name: Install required packages for web display
    become: true
    yum:
      name:
        - httpd
        - php
        - php-mysqlnd
        - git # for later use
      state: latest

#- name: Install required packages for web display
#  hosts: target3
#  become: true
#  vars:
#    packages:
#      - httpd
#      - php
#      - php-mysqlnd
#      - git # for later use
#  tasks:
#  - with_items: "{{ packages }}"
#    yum: 'name={{ item }} state=present'

  #B
  - name: Firewalld Enable ports 80 for http access
    become: true
    firewalld:
      zone: public
      port: 80/tcp
      permanent: yes
      state: enabled
  #C
  - name: Reload service firewalld
    become: true
    systemd:
      name: firewalld
      state: reloaded
  #D
  - name: 'Configure httpd'
    become: true
    shell: sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf
    args:
      warn: false

  #E
  - name: Start httpd
    become: true
    service:
      name: httpd
      state: started
      enabled: yes
  #F
  - name: 'Download code and placed on web directory'
    become: true
    command: 'git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/'

  #G
  - name: 'Update index.php file to connect to the right DB'
    become: true
    shell: sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php
    args:
      warn: false

  #H
  - name: 'Update index.php file to connect to the right DB'
    become: true
    shell: sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php
    args:
      warn: false

  #A
  - name: 'A simple test with curl'
    shell: curl http://localhost
    register: command_output

  - debug:
      var: command_output.stdout_lines
